### ISSUE TITLE
Autostart and Daemonize

### ISSUE THREAD

**Issue by max605b** [tamaloa/newrelic_passenger_plugin#5]
I really like the information provided by this plugin.  How are people setting up Linux systems to autostart the agent and run in the background?

Two problems I've encountered.  First, the path to newrelic_plugin.yml is relative to the current working directory, which makes it difficult to start via an /etc/init.d script.

Second, while I got an /etc/init.d script to work, starting the agent blocks, rather than running as a headless daemon.

How have others addressed this?

**Comment by tamaloa** [comment]
Information on starting a daemonized agent is added to the README.
