### ISSUE TITLE
It doesn't support Passenger 5 Standalone

### ISSUE THREAD

**Issue by mabdelfattah** [tamaloa/newrelic_passenger_plugin#8]
1st. Passenger version in the config file should be 3 or 4
2nd. Passenger standalone is not being added to Gemfile.

**Comment by tamaloa** [comment]
I saw you started working on support for passenger 5.
I would happily merge a PR for support of Passenger 5. Please do include a test output for passenger 5 stats commands. I suppose they have not changed the format but anyway.

I do not understand your second point. This plugin is meant to work standalone (i.e. not being embedded into the application which is being served by passenger). Therefor it is expected to have passenger executables available system wide. You can always configure the paths to the executables to meet your specific system.

**Comment by tamaloa** [comment]
Passenger 5 is now fully supported
