### ISSUE TITLE
Error message on launch

### ISSUE THREAD

**Issue by ddujisin** [tamaloa/newrelic_passenger_plugin#9]
Hi,

When I try the sudo ./newrelic_passenger_agent command, I get this error:

/usr/bin/env: ruby: No such file or directory

config file:

newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: XXXXXXXXXXXXXX(replaced)
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
agents:
  passenger:
    # Adjust the path to your passenger commands as appropriate
    passenger_status: '~/.rvm/gems/ruby-2.1.1/bin/passenger-status'
    passenger_memory_stats: '~/.rvm/gems/ruby-2.1.1/bin/passenger-memory-stats'
    passenger_version: 4 #May be 3 or 4

**Comment by tamaloa** [comment]
Your environment should provide a ruby in the /usr/bin/env path - rvm should normally take care of this. You can edit the newrelic_passenger_agent.rb file to use a different path (first line of file) if needed. But really this should be present :)
